// This file was auto-generated by data/names.py
#![allow(non_upper_case_globals)]
use names::PokeName;

pub const Bulbasaur: PokeName = PokeName {
	id: 1,
	english: "Bulbasaur",
};

pub const Ivysaur: PokeName = PokeName {
	id: 2,
	english: "Ivysaur",
};

pub const Venusaur: PokeName = PokeName {
	id: 3,
	english: "Venusaur",
};

pub const Charmander: PokeName = PokeName {
	id: 4,
	english: "Charmander",
};

pub const Charmeleon: PokeName = PokeName {
	id: 5,
	english: "Charmeleon",
};

pub const Charizard: PokeName = PokeName {
	id: 6,
	english: "Charizard",
};

pub const Squirtle: PokeName = PokeName {
	id: 7,
	english: "Squirtle",
};

pub const Wartortle: PokeName = PokeName {
	id: 8,
	english: "Wartortle",
};

pub const Blastoise: PokeName = PokeName {
	id: 9,
	english: "Blastoise",
};

pub const Caterpie: PokeName = PokeName {
	id: 10,
	english: "Caterpie",
};

pub const Metapod: PokeName = PokeName {
	id: 11,
	english: "Metapod",
};

pub const Butterfree: PokeName = PokeName {
	id: 12,
	english: "Butterfree",
};

pub const Weedle: PokeName = PokeName {
	id: 13,
	english: "Weedle",
};

pub const Kakuna: PokeName = PokeName {
	id: 14,
	english: "Kakuna",
};

pub const Beedrill: PokeName = PokeName {
	id: 15,
	english: "Beedrill",
};

pub const Pidgey: PokeName = PokeName {
	id: 16,
	english: "Pidgey",
};

pub const Pidgeotto: PokeName = PokeName {
	id: 17,
	english: "Pidgeotto",
};

pub const Pidgeot: PokeName = PokeName {
	id: 18,
	english: "Pidgeot",
};

pub const Rattata: PokeName = PokeName {
	id: 19,
	english: "Rattata",
};

pub const Raticate: PokeName = PokeName {
	id: 20,
	english: "Raticate",
};

pub const Spearow: PokeName = PokeName {
	id: 21,
	english: "Spearow",
};

pub const Fearow: PokeName = PokeName {
	id: 22,
	english: "Fearow",
};

pub const Ekans: PokeName = PokeName {
	id: 23,
	english: "Ekans",
};

pub const Arbok: PokeName = PokeName {
	id: 24,
	english: "Arbok",
};

pub const Pikachu: PokeName = PokeName {
	id: 25,
	english: "Pikachu",
};

pub const Raichu: PokeName = PokeName {
	id: 26,
	english: "Raichu",
};

pub const Sandshrew: PokeName = PokeName {
	id: 27,
	english: "Sandshrew",
};

pub const Sandslash: PokeName = PokeName {
	id: 28,
	english: "Sandslash",
};

pub const NidoranFemale: PokeName = PokeName {
	id: 29,
	english: "Nidoran♀",
};

pub const Nidorina: PokeName = PokeName {
	id: 30,
	english: "Nidorina",
};

pub const Nidoqueen: PokeName = PokeName {
	id: 31,
	english: "Nidoqueen",
};

pub const NidoranMale: PokeName = PokeName {
	id: 32,
	english: "Nidoran♂",
};

pub const Nidorino: PokeName = PokeName {
	id: 33,
	english: "Nidorino",
};

pub const Nidoking: PokeName = PokeName {
	id: 34,
	english: "Nidoking",
};

pub const Clefairy: PokeName = PokeName {
	id: 35,
	english: "Clefairy",
};

pub const Clefable: PokeName = PokeName {
	id: 36,
	english: "Clefable",
};

pub const Vulpix: PokeName = PokeName {
	id: 37,
	english: "Vulpix",
};

pub const Ninetales: PokeName = PokeName {
	id: 38,
	english: "Ninetales",
};

pub const Jigglypuff: PokeName = PokeName {
	id: 39,
	english: "Jigglypuff",
};

pub const Wigglytuff: PokeName = PokeName {
	id: 40,
	english: "Wigglytuff",
};

pub const Zubat: PokeName = PokeName {
	id: 41,
	english: "Zubat",
};

pub const Golbat: PokeName = PokeName {
	id: 42,
	english: "Golbat",
};

pub const Oddish: PokeName = PokeName {
	id: 43,
	english: "Oddish",
};

pub const Gloom: PokeName = PokeName {
	id: 44,
	english: "Gloom",
};

pub const Vileplume: PokeName = PokeName {
	id: 45,
	english: "Vileplume",
};

pub const Paras: PokeName = PokeName {
	id: 46,
	english: "Paras",
};

pub const Parasect: PokeName = PokeName {
	id: 47,
	english: "Parasect",
};

pub const Venonat: PokeName = PokeName {
	id: 48,
	english: "Venonat",
};

pub const Venomoth: PokeName = PokeName {
	id: 49,
	english: "Venomoth",
};

pub const Diglett: PokeName = PokeName {
	id: 50,
	english: "Diglett",
};

pub const Dugtrio: PokeName = PokeName {
	id: 51,
	english: "Dugtrio",
};

pub const Meowth: PokeName = PokeName {
	id: 52,
	english: "Meowth",
};

pub const Persian: PokeName = PokeName {
	id: 53,
	english: "Persian",
};

pub const Psyduck: PokeName = PokeName {
	id: 54,
	english: "Psyduck",
};

pub const Golduck: PokeName = PokeName {
	id: 55,
	english: "Golduck",
};

pub const Mankey: PokeName = PokeName {
	id: 56,
	english: "Mankey",
};

pub const Primeape: PokeName = PokeName {
	id: 57,
	english: "Primeape",
};

pub const Growlithe: PokeName = PokeName {
	id: 58,
	english: "Growlithe",
};

pub const Arcanine: PokeName = PokeName {
	id: 59,
	english: "Arcanine",
};

pub const Poliwag: PokeName = PokeName {
	id: 60,
	english: "Poliwag",
};

pub const Poliwhirl: PokeName = PokeName {
	id: 61,
	english: "Poliwhirl",
};

pub const Poliwrath: PokeName = PokeName {
	id: 62,
	english: "Poliwrath",
};

pub const Abra: PokeName = PokeName {
	id: 63,
	english: "Abra",
};

pub const Kadabra: PokeName = PokeName {
	id: 64,
	english: "Kadabra",
};

pub const Alakazam: PokeName = PokeName {
	id: 65,
	english: "Alakazam",
};

pub const Machop: PokeName = PokeName {
	id: 66,
	english: "Machop",
};

pub const Machoke: PokeName = PokeName {
	id: 67,
	english: "Machoke",
};

pub const Machamp: PokeName = PokeName {
	id: 68,
	english: "Machamp",
};

pub const Bellsprout: PokeName = PokeName {
	id: 69,
	english: "Bellsprout",
};

pub const Weepinbell: PokeName = PokeName {
	id: 70,
	english: "Weepinbell",
};

pub const Victreebel: PokeName = PokeName {
	id: 71,
	english: "Victreebel",
};

pub const Tentacool: PokeName = PokeName {
	id: 72,
	english: "Tentacool",
};

pub const Tentacruel: PokeName = PokeName {
	id: 73,
	english: "Tentacruel",
};

pub const Geodude: PokeName = PokeName {
	id: 74,
	english: "Geodude",
};

pub const Graveler: PokeName = PokeName {
	id: 75,
	english: "Graveler",
};

pub const Golem: PokeName = PokeName {
	id: 76,
	english: "Golem",
};

pub const Ponyta: PokeName = PokeName {
	id: 77,
	english: "Ponyta",
};

pub const Rapidash: PokeName = PokeName {
	id: 78,
	english: "Rapidash",
};

pub const Slowpoke: PokeName = PokeName {
	id: 79,
	english: "Slowpoke",
};

pub const Slowbro: PokeName = PokeName {
	id: 80,
	english: "Slowbro",
};

pub const Magnemite: PokeName = PokeName {
	id: 81,
	english: "Magnemite",
};

pub const Magneton: PokeName = PokeName {
	id: 82,
	english: "Magneton",
};

pub const Farfetchd: PokeName = PokeName {
	id: 83,
	english: "Farfetch'd",
};

pub const Doduo: PokeName = PokeName {
	id: 84,
	english: "Doduo",
};

pub const Dodrio: PokeName = PokeName {
	id: 85,
	english: "Dodrio",
};

pub const Seel: PokeName = PokeName {
	id: 86,
	english: "Seel",
};

pub const Dewgong: PokeName = PokeName {
	id: 87,
	english: "Dewgong",
};

pub const Grimer: PokeName = PokeName {
	id: 88,
	english: "Grimer",
};

pub const Muk: PokeName = PokeName {
	id: 89,
	english: "Muk",
};

pub const Shellder: PokeName = PokeName {
	id: 90,
	english: "Shellder",
};

pub const Cloyster: PokeName = PokeName {
	id: 91,
	english: "Cloyster",
};

pub const Gastly: PokeName = PokeName {
	id: 92,
	english: "Gastly",
};

pub const Haunter: PokeName = PokeName {
	id: 93,
	english: "Haunter",
};

pub const Gengar: PokeName = PokeName {
	id: 94,
	english: "Gengar",
};

pub const Onix: PokeName = PokeName {
	id: 95,
	english: "Onix",
};

pub const Drowzee: PokeName = PokeName {
	id: 96,
	english: "Drowzee",
};

pub const Hypno: PokeName = PokeName {
	id: 97,
	english: "Hypno",
};

pub const Krabby: PokeName = PokeName {
	id: 98,
	english: "Krabby",
};

pub const Kingler: PokeName = PokeName {
	id: 99,
	english: "Kingler",
};

pub const Voltorb: PokeName = PokeName {
	id: 100,
	english: "Voltorb",
};

pub const Electrode: PokeName = PokeName {
	id: 101,
	english: "Electrode",
};

pub const Exeggcute: PokeName = PokeName {
	id: 102,
	english: "Exeggcute",
};

pub const Exeggutor: PokeName = PokeName {
	id: 103,
	english: "Exeggutor",
};

pub const Cubone: PokeName = PokeName {
	id: 104,
	english: "Cubone",
};

pub const Marowak: PokeName = PokeName {
	id: 105,
	english: "Marowak",
};

pub const Hitmonlee: PokeName = PokeName {
	id: 106,
	english: "Hitmonlee",
};

pub const Hitmonchan: PokeName = PokeName {
	id: 107,
	english: "Hitmonchan",
};

pub const Lickitung: PokeName = PokeName {
	id: 108,
	english: "Lickitung",
};

pub const Koffing: PokeName = PokeName {
	id: 109,
	english: "Koffing",
};

pub const Weezing: PokeName = PokeName {
	id: 110,
	english: "Weezing",
};

pub const Rhyhorn: PokeName = PokeName {
	id: 111,
	english: "Rhyhorn",
};

pub const Rhydon: PokeName = PokeName {
	id: 112,
	english: "Rhydon",
};

pub const Chansey: PokeName = PokeName {
	id: 113,
	english: "Chansey",
};

pub const Tangela: PokeName = PokeName {
	id: 114,
	english: "Tangela",
};

pub const Kangaskhan: PokeName = PokeName {
	id: 115,
	english: "Kangaskhan",
};

pub const Horsea: PokeName = PokeName {
	id: 116,
	english: "Horsea",
};

pub const Seadra: PokeName = PokeName {
	id: 117,
	english: "Seadra",
};

pub const Goldeen: PokeName = PokeName {
	id: 118,
	english: "Goldeen",
};

pub const Seaking: PokeName = PokeName {
	id: 119,
	english: "Seaking",
};

pub const Staryu: PokeName = PokeName {
	id: 120,
	english: "Staryu",
};

pub const Starmie: PokeName = PokeName {
	id: 121,
	english: "Starmie",
};

pub const MrMime: PokeName = PokeName {
	id: 122,
	english: "Mr. Mime",
};

pub const Scyther: PokeName = PokeName {
	id: 123,
	english: "Scyther",
};

pub const Jynx: PokeName = PokeName {
	id: 124,
	english: "Jynx",
};

pub const Electabuzz: PokeName = PokeName {
	id: 125,
	english: "Electabuzz",
};

pub const Magmar: PokeName = PokeName {
	id: 126,
	english: "Magmar",
};

pub const Pinsir: PokeName = PokeName {
	id: 127,
	english: "Pinsir",
};

pub const Tauros: PokeName = PokeName {
	id: 128,
	english: "Tauros",
};

pub const Magikarp: PokeName = PokeName {
	id: 129,
	english: "Magikarp",
};

pub const Gyarados: PokeName = PokeName {
	id: 130,
	english: "Gyarados",
};

pub const Lapras: PokeName = PokeName {
	id: 131,
	english: "Lapras",
};

pub const Ditto: PokeName = PokeName {
	id: 132,
	english: "Ditto",
};

pub const Eevee: PokeName = PokeName {
	id: 133,
	english: "Eevee",
};

pub const Vaporeon: PokeName = PokeName {
	id: 134,
	english: "Vaporeon",
};

pub const Jolteon: PokeName = PokeName {
	id: 135,
	english: "Jolteon",
};

pub const Flareon: PokeName = PokeName {
	id: 136,
	english: "Flareon",
};

pub const Porygon: PokeName = PokeName {
	id: 137,
	english: "Porygon",
};

pub const Omanyte: PokeName = PokeName {
	id: 138,
	english: "Omanyte",
};

pub const Omastar: PokeName = PokeName {
	id: 139,
	english: "Omastar",
};

pub const Kabuto: PokeName = PokeName {
	id: 140,
	english: "Kabuto",
};

pub const Kabutops: PokeName = PokeName {
	id: 141,
	english: "Kabutops",
};

pub const Aerodactyl: PokeName = PokeName {
	id: 142,
	english: "Aerodactyl",
};

pub const Snorlax: PokeName = PokeName {
	id: 143,
	english: "Snorlax",
};

pub const Articuno: PokeName = PokeName {
	id: 144,
	english: "Articuno",
};

pub const Zapdos: PokeName = PokeName {
	id: 145,
	english: "Zapdos",
};

pub const Moltres: PokeName = PokeName {
	id: 146,
	english: "Moltres",
};

pub const Dratini: PokeName = PokeName {
	id: 147,
	english: "Dratini",
};

pub const Dragonair: PokeName = PokeName {
	id: 148,
	english: "Dragonair",
};

pub const Dragonite: PokeName = PokeName {
	id: 149,
	english: "Dragonite",
};

pub const Mewtwo: PokeName = PokeName {
	id: 150,
	english: "Mewtwo",
};

pub const Mew: PokeName = PokeName {
	id: 151,
	english: "Mew",
};

pub const Chikorita: PokeName = PokeName {
	id: 152,
	english: "Chikorita",
};

pub const Bayleef: PokeName = PokeName {
	id: 153,
	english: "Bayleef",
};

pub const Meganium: PokeName = PokeName {
	id: 154,
	english: "Meganium",
};

pub const Cyndaquil: PokeName = PokeName {
	id: 155,
	english: "Cyndaquil",
};

pub const Quilava: PokeName = PokeName {
	id: 156,
	english: "Quilava",
};

pub const Typhlosion: PokeName = PokeName {
	id: 157,
	english: "Typhlosion",
};

pub const Totodile: PokeName = PokeName {
	id: 158,
	english: "Totodile",
};

pub const Croconaw: PokeName = PokeName {
	id: 159,
	english: "Croconaw",
};

pub const Feraligatr: PokeName = PokeName {
	id: 160,
	english: "Feraligatr",
};

pub const Sentret: PokeName = PokeName {
	id: 161,
	english: "Sentret",
};

pub const Furret: PokeName = PokeName {
	id: 162,
	english: "Furret",
};

pub const Hoothoot: PokeName = PokeName {
	id: 163,
	english: "Hoothoot",
};

pub const Noctowl: PokeName = PokeName {
	id: 164,
	english: "Noctowl",
};

pub const Ledyba: PokeName = PokeName {
	id: 165,
	english: "Ledyba",
};

pub const Ledian: PokeName = PokeName {
	id: 166,
	english: "Ledian",
};

pub const Spinarak: PokeName = PokeName {
	id: 167,
	english: "Spinarak",
};

pub const Ariados: PokeName = PokeName {
	id: 168,
	english: "Ariados",
};

pub const Crobat: PokeName = PokeName {
	id: 169,
	english: "Crobat",
};

pub const Chinchou: PokeName = PokeName {
	id: 170,
	english: "Chinchou",
};

pub const Lanturn: PokeName = PokeName {
	id: 171,
	english: "Lanturn",
};

pub const Pichu: PokeName = PokeName {
	id: 172,
	english: "Pichu",
};

pub const Cleffa: PokeName = PokeName {
	id: 173,
	english: "Cleffa",
};

pub const Igglybuff: PokeName = PokeName {
	id: 174,
	english: "Igglybuff",
};

pub const Togepi: PokeName = PokeName {
	id: 175,
	english: "Togepi",
};

pub const Togetic: PokeName = PokeName {
	id: 176,
	english: "Togetic",
};

pub const Natu: PokeName = PokeName {
	id: 177,
	english: "Natu",
};

pub const Xatu: PokeName = PokeName {
	id: 178,
	english: "Xatu",
};

pub const Mareep: PokeName = PokeName {
	id: 179,
	english: "Mareep",
};

pub const Flaaffy: PokeName = PokeName {
	id: 180,
	english: "Flaaffy",
};

pub const Ampharos: PokeName = PokeName {
	id: 181,
	english: "Ampharos",
};

pub const Bellossom: PokeName = PokeName {
	id: 182,
	english: "Bellossom",
};

pub const Marill: PokeName = PokeName {
	id: 183,
	english: "Marill",
};

pub const Azumarill: PokeName = PokeName {
	id: 184,
	english: "Azumarill",
};

pub const Sudowoodo: PokeName = PokeName {
	id: 185,
	english: "Sudowoodo",
};

pub const Politoed: PokeName = PokeName {
	id: 186,
	english: "Politoed",
};

pub const Hoppip: PokeName = PokeName {
	id: 187,
	english: "Hoppip",
};

pub const Skiploom: PokeName = PokeName {
	id: 188,
	english: "Skiploom",
};

pub const Jumpluff: PokeName = PokeName {
	id: 189,
	english: "Jumpluff",
};

pub const Aipom: PokeName = PokeName {
	id: 190,
	english: "Aipom",
};

pub const Sunkern: PokeName = PokeName {
	id: 191,
	english: "Sunkern",
};

pub const Sunflora: PokeName = PokeName {
	id: 192,
	english: "Sunflora",
};

pub const Yanma: PokeName = PokeName {
	id: 193,
	english: "Yanma",
};

pub const Wooper: PokeName = PokeName {
	id: 194,
	english: "Wooper",
};

pub const Quagsire: PokeName = PokeName {
	id: 195,
	english: "Quagsire",
};

pub const Espeon: PokeName = PokeName {
	id: 196,
	english: "Espeon",
};

pub const Umbreon: PokeName = PokeName {
	id: 197,
	english: "Umbreon",
};

pub const Murkrow: PokeName = PokeName {
	id: 198,
	english: "Murkrow",
};

pub const Slowking: PokeName = PokeName {
	id: 199,
	english: "Slowking",
};

pub const Misdreavus: PokeName = PokeName {
	id: 200,
	english: "Misdreavus",
};

pub const Unown: PokeName = PokeName {
	id: 201,
	english: "Unown",
};

pub const Wobbuffet: PokeName = PokeName {
	id: 202,
	english: "Wobbuffet",
};

pub const Girafarig: PokeName = PokeName {
	id: 203,
	english: "Girafarig",
};

pub const Pineco: PokeName = PokeName {
	id: 204,
	english: "Pineco",
};

pub const Forretress: PokeName = PokeName {
	id: 205,
	english: "Forretress",
};

pub const Dunsparce: PokeName = PokeName {
	id: 206,
	english: "Dunsparce",
};

pub const Gligar: PokeName = PokeName {
	id: 207,
	english: "Gligar",
};

pub const Steelix: PokeName = PokeName {
	id: 208,
	english: "Steelix",
};

pub const Snubbull: PokeName = PokeName {
	id: 209,
	english: "Snubbull",
};

pub const Granbull: PokeName = PokeName {
	id: 210,
	english: "Granbull",
};

pub const Qwilfish: PokeName = PokeName {
	id: 211,
	english: "Qwilfish",
};

pub const Scizor: PokeName = PokeName {
	id: 212,
	english: "Scizor",
};

pub const Shuckle: PokeName = PokeName {
	id: 213,
	english: "Shuckle",
};

pub const Heracross: PokeName = PokeName {
	id: 214,
	english: "Heracross",
};

pub const Sneasel: PokeName = PokeName {
	id: 215,
	english: "Sneasel",
};

pub const Teddiursa: PokeName = PokeName {
	id: 216,
	english: "Teddiursa",
};

pub const Ursaring: PokeName = PokeName {
	id: 217,
	english: "Ursaring",
};

pub const Slugma: PokeName = PokeName {
	id: 218,
	english: "Slugma",
};

pub const Magcargo: PokeName = PokeName {
	id: 219,
	english: "Magcargo",
};

pub const Swinub: PokeName = PokeName {
	id: 220,
	english: "Swinub",
};

pub const Piloswine: PokeName = PokeName {
	id: 221,
	english: "Piloswine",
};

pub const Corsola: PokeName = PokeName {
	id: 222,
	english: "Corsola",
};

pub const Remoraid: PokeName = PokeName {
	id: 223,
	english: "Remoraid",
};

pub const Octillery: PokeName = PokeName {
	id: 224,
	english: "Octillery",
};

pub const Delibird: PokeName = PokeName {
	id: 225,
	english: "Delibird",
};

pub const Mantine: PokeName = PokeName {
	id: 226,
	english: "Mantine",
};

pub const Skarmory: PokeName = PokeName {
	id: 227,
	english: "Skarmory",
};

pub const Houndour: PokeName = PokeName {
	id: 228,
	english: "Houndour",
};

pub const Houndoom: PokeName = PokeName {
	id: 229,
	english: "Houndoom",
};

pub const Kingdra: PokeName = PokeName {
	id: 230,
	english: "Kingdra",
};

pub const Phanpy: PokeName = PokeName {
	id: 231,
	english: "Phanpy",
};

pub const Donphan: PokeName = PokeName {
	id: 232,
	english: "Donphan",
};

pub const Porygon2: PokeName = PokeName {
	id: 233,
	english: "Porygon2",
};

pub const Stantler: PokeName = PokeName {
	id: 234,
	english: "Stantler",
};

pub const Smeargle: PokeName = PokeName {
	id: 235,
	english: "Smeargle",
};

pub const Tyrogue: PokeName = PokeName {
	id: 236,
	english: "Tyrogue",
};

pub const Hitmontop: PokeName = PokeName {
	id: 237,
	english: "Hitmontop",
};

pub const Smoochum: PokeName = PokeName {
	id: 238,
	english: "Smoochum",
};

pub const Elekid: PokeName = PokeName {
	id: 239,
	english: "Elekid",
};

pub const Magby: PokeName = PokeName {
	id: 240,
	english: "Magby",
};

pub const Miltank: PokeName = PokeName {
	id: 241,
	english: "Miltank",
};

pub const Blissey: PokeName = PokeName {
	id: 242,
	english: "Blissey",
};

pub const Raikou: PokeName = PokeName {
	id: 243,
	english: "Raikou",
};

pub const Entei: PokeName = PokeName {
	id: 244,
	english: "Entei",
};

pub const Suicune: PokeName = PokeName {
	id: 245,
	english: "Suicune",
};

pub const Larvitar: PokeName = PokeName {
	id: 246,
	english: "Larvitar",
};

pub const Pupitar: PokeName = PokeName {
	id: 247,
	english: "Pupitar",
};

pub const Tyranitar: PokeName = PokeName {
	id: 248,
	english: "Tyranitar",
};

pub const Lugia: PokeName = PokeName {
	id: 249,
	english: "Lugia",
};

pub const HoOh: PokeName = PokeName {
	id: 250,
	english: "Ho-Oh",
};

pub const Celebi: PokeName = PokeName {
	id: 251,
	english: "Celebi",
};

