// Thie file was auto-generated using data/base_stats.py
use pokemon_data::SpeciesData;
use types::PokeType;

pub const SPECIES: &'static [SpeciesData] = &[
	SpeciesData {
		id: 1,
		attack: 118,
		defense: 118,
		stamina: 90,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 2,
		attack: 151,
		defense: 151,
		stamina: 120,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 3,
		attack: 198,
		defense: 198,
		stamina: 160,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 4,
		attack: 116,
		defense: 96,
		stamina: 78,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 5,
		attack: 158,
		defense: 129,
		stamina: 116,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 6,
		attack: 223,
		defense: 176,
		stamina: 156,
		primary_type: PokeType::Fire,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 7,
		attack: 94,
		defense: 122,
		stamina: 88,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 8,
		attack: 126,
		defense: 155,
		stamina: 118,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 9,
		attack: 171,
		defense: 210,
		stamina: 158,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 10,
		attack: 55,
		defense: 62,
		stamina: 90,
		primary_type: PokeType::Bug,
		secondary_type: None,
	},
	SpeciesData {
		id: 11,
		attack: 45,
		defense: 94,
		stamina: 100,
		primary_type: PokeType::Bug,
		secondary_type: None,
	},
	SpeciesData {
		id: 12,
		attack: 167,
		defense: 151,
		stamina: 120,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 13,
		attack: 63,
		defense: 55,
		stamina: 80,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 14,
		attack: 46,
		defense: 86,
		stamina: 90,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 15,
		attack: 169,
		defense: 150,
		stamina: 130,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 16,
		attack: 85,
		defense: 76,
		stamina: 80,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 17,
		attack: 117,
		defense: 108,
		stamina: 126,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 18,
		attack: 166,
		defense: 157,
		stamina: 166,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 19,
		attack: 103,
		defense: 70,
		stamina: 60,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 20,
		attack: 161,
		defense: 144,
		stamina: 110,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 21,
		attack: 112,
		defense: 61,
		stamina: 80,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 22,
		attack: 182,
		defense: 135,
		stamina: 130,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 23,
		attack: 110,
		defense: 102,
		stamina: 70,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 24,
		attack: 167,
		defense: 158,
		stamina: 120,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 25,
		attack: 112,
		defense: 101,
		stamina: 70,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 26,
		attack: 193,
		defense: 165,
		stamina: 120,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 27,
		attack: 126,
		defense: 145,
		stamina: 100,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 28,
		attack: 182,
		defense: 202,
		stamina: 150,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 29,
		attack: 86,
		defense: 94,
		stamina: 110,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 30,
		attack: 117,
		defense: 126,
		stamina: 140,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 31,
		attack: 180,
		defense: 174,
		stamina: 180,
		primary_type: PokeType::Poison,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 32,
		attack: 105,
		defense: 76,
		stamina: 92,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 33,
		attack: 137,
		defense: 112,
		stamina: 122,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 34,
		attack: 204,
		defense: 157,
		stamina: 162,
		primary_type: PokeType::Poison,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 35,
		attack: 107,
		defense: 116,
		stamina: 140,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 36,
		attack: 178,
		defense: 171,
		stamina: 190,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 37,
		attack: 96,
		defense: 122,
		stamina: 76,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 38,
		attack: 169,
		defense: 204,
		stamina: 146,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 39,
		attack: 80,
		defense: 44,
		stamina: 230,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 40,
		attack: 156,
		defense: 93,
		stamina: 280,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 41,
		attack: 83,
		defense: 76,
		stamina: 80,
		primary_type: PokeType::Poison,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 42,
		attack: 161,
		defense: 153,
		stamina: 150,
		primary_type: PokeType::Poison,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 43,
		attack: 131,
		defense: 116,
		stamina: 90,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 44,
		attack: 153,
		defense: 139,
		stamina: 120,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 45,
		attack: 202,
		defense: 170,
		stamina: 150,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 46,
		attack: 121,
		defense: 99,
		stamina: 70,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Grass),
	},
	SpeciesData {
		id: 47,
		attack: 165,
		defense: 146,
		stamina: 120,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Grass),
	},
	SpeciesData {
		id: 48,
		attack: 100,
		defense: 102,
		stamina: 120,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 49,
		attack: 179,
		defense: 150,
		stamina: 140,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 50,
		attack: 109,
		defense: 88,
		stamina: 20,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 51,
		attack: 167,
		defense: 147,
		stamina: 70,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 52,
		attack: 92,
		defense: 81,
		stamina: 80,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 53,
		attack: 150,
		defense: 139,
		stamina: 130,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 54,
		attack: 122,
		defense: 96,
		stamina: 100,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 55,
		attack: 191,
		defense: 163,
		stamina: 160,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 56,
		attack: 148,
		defense: 87,
		stamina: 80,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 57,
		attack: 207,
		defense: 144,
		stamina: 130,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 58,
		attack: 136,
		defense: 96,
		stamina: 110,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 59,
		attack: 227,
		defense: 166,
		stamina: 180,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 60,
		attack: 101,
		defense: 82,
		stamina: 80,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 61,
		attack: 130,
		defense: 130,
		stamina: 130,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 62,
		attack: 182,
		defense: 187,
		stamina: 180,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Fighting),
	},
	SpeciesData {
		id: 63,
		attack: 195,
		defense: 103,
		stamina: 50,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 64,
		attack: 232,
		defense: 138,
		stamina: 80,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 65,
		attack: 271,
		defense: 194,
		stamina: 110,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 66,
		attack: 137,
		defense: 88,
		stamina: 140,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 67,
		attack: 177,
		defense: 130,
		stamina: 160,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 68,
		attack: 234,
		defense: 162,
		stamina: 180,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 69,
		attack: 139,
		defense: 64,
		stamina: 100,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 70,
		attack: 172,
		defense: 95,
		stamina: 130,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 71,
		attack: 207,
		defense: 138,
		stamina: 160,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 72,
		attack: 97,
		defense: 182,
		stamina: 80,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 73,
		attack: 166,
		defense: 237,
		stamina: 160,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 74,
		attack: 132,
		defense: 163,
		stamina: 80,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 75,
		attack: 164,
		defense: 196,
		stamina: 110,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 76,
		attack: 211,
		defense: 229,
		stamina: 160,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 77,
		attack: 170,
		defense: 132,
		stamina: 100,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 78,
		attack: 207,
		defense: 167,
		stamina: 130,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 79,
		attack: 109,
		defense: 109,
		stamina: 180,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 80,
		attack: 177,
		defense: 194,
		stamina: 190,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 81,
		attack: 165,
		defense: 128,
		stamina: 50,
		primary_type: PokeType::Electric,
		secondary_type: Some(PokeType::Steel),
	},
	SpeciesData {
		id: 82,
		attack: 223,
		defense: 182,
		stamina: 100,
		primary_type: PokeType::Electric,
		secondary_type: Some(PokeType::Steel),
	},
	SpeciesData {
		id: 83,
		attack: 124,
		defense: 118,
		stamina: 104,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 84,
		attack: 158,
		defense: 88,
		stamina: 70,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 85,
		attack: 218,
		defense: 145,
		stamina: 120,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 86,
		attack: 85,
		defense: 128,
		stamina: 130,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 87,
		attack: 139,
		defense: 184,
		stamina: 180,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Ice),
	},
	SpeciesData {
		id: 88,
		attack: 135,
		defense: 90,
		stamina: 160,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 89,
		attack: 190,
		defense: 184,
		stamina: 210,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 90,
		attack: 116,
		defense: 168,
		stamina: 60,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 91,
		attack: 186,
		defense: 323,
		stamina: 100,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Ice),
	},
	SpeciesData {
		id: 92,
		attack: 186,
		defense: 70,
		stamina: 60,
		primary_type: PokeType::Ghost,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 93,
		attack: 223,
		defense: 112,
		stamina: 90,
		primary_type: PokeType::Ghost,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 94,
		attack: 261,
		defense: 156,
		stamina: 120,
		primary_type: PokeType::Ghost,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 95,
		attack: 85,
		defense: 288,
		stamina: 70,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 96,
		attack: 89,
		defense: 158,
		stamina: 120,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 97,
		attack: 144,
		defense: 215,
		stamina: 170,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 98,
		attack: 181,
		defense: 156,
		stamina: 60,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 99,
		attack: 240,
		defense: 214,
		stamina: 110,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 100,
		attack: 109,
		defense: 114,
		stamina: 80,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 101,
		attack: 173,
		defense: 179,
		stamina: 120,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 102,
		attack: 107,
		defense: 140,
		stamina: 120,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 103,
		attack: 233,
		defense: 158,
		stamina: 190,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 104,
		attack: 90,
		defense: 165,
		stamina: 100,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 105,
		attack: 144,
		defense: 200,
		stamina: 120,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 106,
		attack: 224,
		defense: 211,
		stamina: 100,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 107,
		attack: 193,
		defense: 212,
		stamina: 100,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 108,
		attack: 108,
		defense: 137,
		stamina: 180,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 109,
		attack: 119,
		defense: 164,
		stamina: 80,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 110,
		attack: 174,
		defense: 221,
		stamina: 130,
		primary_type: PokeType::Poison,
		secondary_type: None,
	},
	SpeciesData {
		id: 111,
		attack: 140,
		defense: 157,
		stamina: 160,
		primary_type: PokeType::Ground,
		secondary_type: Some(PokeType::Rock),
	},
	SpeciesData {
		id: 112,
		attack: 222,
		defense: 206,
		stamina: 210,
		primary_type: PokeType::Ground,
		secondary_type: Some(PokeType::Rock),
	},
	SpeciesData {
		id: 113,
		attack: 60,
		defense: 176,
		stamina: 500,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 114,
		attack: 183,
		defense: 205,
		stamina: 130,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 115,
		attack: 181,
		defense: 165,
		stamina: 210,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 116,
		attack: 129,
		defense: 125,
		stamina: 60,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 117,
		attack: 187,
		defense: 182,
		stamina: 110,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 118,
		attack: 123,
		defense: 115,
		stamina: 90,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 119,
		attack: 175,
		defense: 154,
		stamina: 160,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 120,
		attack: 137,
		defense: 112,
		stamina: 60,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 121,
		attack: 210,
		defense: 184,
		stamina: 120,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 122,
		attack: 192,
		defense: 233,
		stamina: 80,
		primary_type: PokeType::Psychic,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 123,
		attack: 218,
		defense: 170,
		stamina: 140,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 124,
		attack: 223,
		defense: 182,
		stamina: 130,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 125,
		attack: 198,
		defense: 173,
		stamina: 130,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 126,
		attack: 206,
		defense: 169,
		stamina: 130,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 127,
		attack: 238,
		defense: 197,
		stamina: 130,
		primary_type: PokeType::Bug,
		secondary_type: None,
	},
	SpeciesData {
		id: 128,
		attack: 198,
		defense: 197,
		stamina: 150,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 129,
		attack: 29,
		defense: 102,
		stamina: 40,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 130,
		attack: 237,
		defense: 197,
		stamina: 190,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 131,
		attack: 165,
		defense: 180,
		stamina: 260,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Ice),
	},
	SpeciesData {
		id: 132,
		attack: 91,
		defense: 91,
		stamina: 96,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 133,
		attack: 104,
		defense: 121,
		stamina: 110,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 134,
		attack: 205,
		defense: 177,
		stamina: 260,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 135,
		attack: 232,
		defense: 201,
		stamina: 130,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 136,
		attack: 246,
		defense: 204,
		stamina: 130,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 137,
		attack: 153,
		defense: 139,
		stamina: 130,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 138,
		attack: 155,
		defense: 174,
		stamina: 70,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Water),
	},
	SpeciesData {
		id: 139,
		attack: 207,
		defense: 227,
		stamina: 140,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Water),
	},
	SpeciesData {
		id: 140,
		attack: 148,
		defense: 162,
		stamina: 60,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Water),
	},
	SpeciesData {
		id: 141,
		attack: 220,
		defense: 203,
		stamina: 120,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Water),
	},
	SpeciesData {
		id: 142,
		attack: 221,
		defense: 164,
		stamina: 160,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 143,
		attack: 190,
		defense: 190,
		stamina: 320,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 144,
		attack: 192,
		defense: 249,
		stamina: 180,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 145,
		attack: 253,
		defense: 188,
		stamina: 180,
		primary_type: PokeType::Electric,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 146,
		attack: 251,
		defense: 184,
		stamina: 180,
		primary_type: PokeType::Fire,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 147,
		attack: 119,
		defense: 94,
		stamina: 82,
		primary_type: PokeType::Dragon,
		secondary_type: None,
	},
	SpeciesData {
		id: 148,
		attack: 163,
		defense: 138,
		stamina: 122,
		primary_type: PokeType::Dragon,
		secondary_type: None,
	},
	SpeciesData {
		id: 149,
		attack: 263,
		defense: 201,
		stamina: 182,
		primary_type: PokeType::Dragon,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 150,
		attack: 300,
		defense: 182,
		stamina: 193,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 151,
		attack: 210,
		defense: 210,
		stamina: 200,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 152,
		attack: 92,
		defense: 122,
		stamina: 90,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 153,
		attack: 122,
		defense: 155,
		stamina: 120,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 154,
		attack: 168,
		defense: 202,
		stamina: 160,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 155,
		attack: 116,
		defense: 96,
		stamina: 78,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 156,
		attack: 158,
		defense: 129,
		stamina: 116,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 157,
		attack: 223,
		defense: 176,
		stamina: 156,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 158,
		attack: 117,
		defense: 116,
		stamina: 100,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 159,
		attack: 150,
		defense: 151,
		stamina: 130,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 160,
		attack: 205,
		defense: 197,
		stamina: 170,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 161,
		attack: 79,
		defense: 77,
		stamina: 70,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 162,
		attack: 148,
		defense: 130,
		stamina: 170,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 163,
		attack: 67,
		defense: 101,
		stamina: 120,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 164,
		attack: 145,
		defense: 179,
		stamina: 200,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 165,
		attack: 72,
		defense: 142,
		stamina: 80,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 166,
		attack: 107,
		defense: 209,
		stamina: 110,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 167,
		attack: 105,
		defense: 73,
		stamina: 80,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 168,
		attack: 161,
		defense: 128,
		stamina: 140,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 169,
		attack: 194,
		defense: 178,
		stamina: 170,
		primary_type: PokeType::Poison,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 170,
		attack: 106,
		defense: 106,
		stamina: 150,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Electric),
	},
	SpeciesData {
		id: 171,
		attack: 146,
		defense: 146,
		stamina: 250,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Electric),
	},
	SpeciesData {
		id: 172,
		attack: 77,
		defense: 63,
		stamina: 40,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 173,
		attack: 75,
		defense: 91,
		stamina: 100,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 174,
		attack: 69,
		defense: 34,
		stamina: 180,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 175,
		attack: 67,
		defense: 116,
		stamina: 70,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 176,
		attack: 139,
		defense: 191,
		stamina: 110,
		primary_type: PokeType::Fairy,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 177,
		attack: 134,
		defense: 89,
		stamina: 80,
		primary_type: PokeType::Psychic,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 178,
		attack: 192,
		defense: 146,
		stamina: 130,
		primary_type: PokeType::Psychic,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 179,
		attack: 114,
		defense: 82,
		stamina: 110,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 180,
		attack: 145,
		defense: 112,
		stamina: 140,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 181,
		attack: 211,
		defense: 172,
		stamina: 180,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 182,
		attack: 169,
		defense: 189,
		stamina: 150,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 183,
		attack: 37,
		defense: 93,
		stamina: 140,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 184,
		attack: 112,
		defense: 152,
		stamina: 200,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Fairy),
	},
	SpeciesData {
		id: 185,
		attack: 167,
		defense: 198,
		stamina: 140,
		primary_type: PokeType::Rock,
		secondary_type: None,
	},
	SpeciesData {
		id: 186,
		attack: 174,
		defense: 192,
		stamina: 180,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 187,
		attack: 67,
		defense: 101,
		stamina: 70,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 188,
		attack: 91,
		defense: 127,
		stamina: 110,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 189,
		attack: 118,
		defense: 197,
		stamina: 150,
		primary_type: PokeType::Grass,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 190,
		attack: 136,
		defense: 112,
		stamina: 110,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 191,
		attack: 55,
		defense: 55,
		stamina: 60,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 192,
		attack: 185,
		defense: 148,
		stamina: 150,
		primary_type: PokeType::Grass,
		secondary_type: None,
	},
	SpeciesData {
		id: 193,
		attack: 154,
		defense: 94,
		stamina: 130,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 194,
		attack: 75,
		defense: 75,
		stamina: 110,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 195,
		attack: 152,
		defense: 152,
		stamina: 190,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 196,
		attack: 261,
		defense: 194,
		stamina: 130,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 197,
		attack: 126,
		defense: 250,
		stamina: 190,
		primary_type: PokeType::Dark,
		secondary_type: None,
	},
	SpeciesData {
		id: 198,
		attack: 175,
		defense: 87,
		stamina: 120,
		primary_type: PokeType::Dark,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 199,
		attack: 177,
		defense: 194,
		stamina: 190,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 200,
		attack: 167,
		defense: 167,
		stamina: 120,
		primary_type: PokeType::Ghost,
		secondary_type: None,
	},
	SpeciesData {
		id: 201,
		attack: 136,
		defense: 91,
		stamina: 96,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 202,
		attack: 60,
		defense: 106,
		stamina: 380,
		primary_type: PokeType::Psychic,
		secondary_type: None,
	},
	SpeciesData {
		id: 203,
		attack: 182,
		defense: 133,
		stamina: 140,
		primary_type: PokeType::Normal,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 204,
		attack: 108,
		defense: 146,
		stamina: 100,
		primary_type: PokeType::Bug,
		secondary_type: None,
	},
	SpeciesData {
		id: 205,
		attack: 161,
		defense: 242,
		stamina: 150,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Steel),
	},
	SpeciesData {
		id: 206,
		attack: 131,
		defense: 131,
		stamina: 200,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 207,
		attack: 143,
		defense: 204,
		stamina: 130,
		primary_type: PokeType::Ground,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 208,
		attack: 148,
		defense: 333,
		stamina: 150,
		primary_type: PokeType::Steel,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 209,
		attack: 137,
		defense: 89,
		stamina: 120,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 210,
		attack: 212,
		defense: 137,
		stamina: 180,
		primary_type: PokeType::Fairy,
		secondary_type: None,
	},
	SpeciesData {
		id: 211,
		attack: 184,
		defense: 148,
		stamina: 130,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Poison),
	},
	SpeciesData {
		id: 212,
		attack: 236,
		defense: 191,
		stamina: 140,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Steel),
	},
	SpeciesData {
		id: 213,
		attack: 17,
		defense: 396,
		stamina: 40,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Rock),
	},
	SpeciesData {
		id: 214,
		attack: 234,
		defense: 189,
		stamina: 160,
		primary_type: PokeType::Bug,
		secondary_type: Some(PokeType::Fighting),
	},
	SpeciesData {
		id: 215,
		attack: 189,
		defense: 157,
		stamina: 110,
		primary_type: PokeType::Dark,
		secondary_type: Some(PokeType::Ice),
	},
	SpeciesData {
		id: 216,
		attack: 142,
		defense: 93,
		stamina: 120,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 217,
		attack: 236,
		defense: 144,
		stamina: 180,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 218,
		attack: 118,
		defense: 71,
		stamina: 80,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 219,
		attack: 139,
		defense: 209,
		stamina: 100,
		primary_type: PokeType::Fire,
		secondary_type: Some(PokeType::Rock),
	},
	SpeciesData {
		id: 220,
		attack: 90,
		defense: 74,
		stamina: 100,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 221,
		attack: 181,
		defense: 147,
		stamina: 200,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 222,
		attack: 118,
		defense: 156,
		stamina: 110,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Rock),
	},
	SpeciesData {
		id: 223,
		attack: 127,
		defense: 69,
		stamina: 70,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 224,
		attack: 197,
		defense: 141,
		stamina: 150,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 225,
		attack: 128,
		defense: 90,
		stamina: 90,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 226,
		attack: 148,
		defense: 260,
		stamina: 130,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 227,
		attack: 148,
		defense: 260,
		stamina: 130,
		primary_type: PokeType::Steel,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 228,
		attack: 152,
		defense: 93,
		stamina: 90,
		primary_type: PokeType::Dark,
		secondary_type: Some(PokeType::Fire),
	},
	SpeciesData {
		id: 229,
		attack: 224,
		defense: 159,
		stamina: 150,
		primary_type: PokeType::Dark,
		secondary_type: Some(PokeType::Fire),
	},
	SpeciesData {
		id: 230,
		attack: 194,
		defense: 194,
		stamina: 150,
		primary_type: PokeType::Water,
		secondary_type: Some(PokeType::Dragon),
	},
	SpeciesData {
		id: 231,
		attack: 107,
		defense: 107,
		stamina: 180,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 232,
		attack: 214,
		defense: 214,
		stamina: 180,
		primary_type: PokeType::Ground,
		secondary_type: None,
	},
	SpeciesData {
		id: 233,
		attack: 198,
		defense: 183,
		stamina: 170,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 234,
		attack: 192,
		defense: 132,
		stamina: 146,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 235,
		attack: 40,
		defense: 88,
		stamina: 110,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 236,
		attack: 64,
		defense: 64,
		stamina: 70,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 237,
		attack: 173,
		defense: 214,
		stamina: 100,
		primary_type: PokeType::Fighting,
		secondary_type: None,
	},
	SpeciesData {
		id: 238,
		attack: 153,
		defense: 116,
		stamina: 90,
		primary_type: PokeType::Ice,
		secondary_type: Some(PokeType::Psychic),
	},
	SpeciesData {
		id: 239,
		attack: 135,
		defense: 110,
		stamina: 90,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 240,
		attack: 151,
		defense: 108,
		stamina: 90,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 241,
		attack: 157,
		defense: 211,
		stamina: 190,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 242,
		attack: 129,
		defense: 229,
		stamina: 510,
		primary_type: PokeType::Normal,
		secondary_type: None,
	},
	SpeciesData {
		id: 243,
		attack: 241,
		defense: 210,
		stamina: 180,
		primary_type: PokeType::Electric,
		secondary_type: None,
	},
	SpeciesData {
		id: 244,
		attack: 235,
		defense: 176,
		stamina: 230,
		primary_type: PokeType::Fire,
		secondary_type: None,
	},
	SpeciesData {
		id: 245,
		attack: 180,
		defense: 235,
		stamina: 200,
		primary_type: PokeType::Water,
		secondary_type: None,
	},
	SpeciesData {
		id: 246,
		attack: 115,
		defense: 93,
		stamina: 100,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 247,
		attack: 155,
		defense: 133,
		stamina: 140,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Ground),
	},
	SpeciesData {
		id: 248,
		attack: 251,
		defense: 212,
		stamina: 200,
		primary_type: PokeType::Rock,
		secondary_type: Some(PokeType::Dark),
	},
	SpeciesData {
		id: 249,
		attack: 193,
		defense: 323,
		stamina: 212,
		primary_type: PokeType::Psychic,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 250,
		attack: 263,
		defense: 301,
		stamina: 212,
		primary_type: PokeType::Fire,
		secondary_type: Some(PokeType::Flying),
	},
	SpeciesData {
		id: 251,
		attack: 210,
		defense: 210,
		stamina: 200,
		primary_type: PokeType::Psychic,
		secondary_type: Some(PokeType::Grass),
	},
];
