import csv

IN_FILE = 'in/pokemon_names.tsv'
OUT_FILE = '../src/names/generated_names.rs'

EXCEPTIONS = {
    'Nidoran♀': 'NidoranFemale',
    'Nidoran♂': 'NidoranMale',
    'Farfetch\'d': 'Farfetchd',
    'Mr. Mime': 'MrMime',
    'Ho-Oh': 'HoOh'
}


def read_in():
    with open(IN_FILE, encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        return list(row for row in reader)


def write(names):
    f = open(OUT_FILE, 'w', encoding='utf-8')

    f.write('// This file was auto-generated by data/names.py\n')
    f.write('#![allow(non_upper_case_globals)]\n')
    f.write('use names::PokeName;\n\n')

    for name in names:
        display_name = EXCEPTIONS.get(name['English'], name['English'])

        f.write('pub const {}: PokeName = PokeName {{\n'.format(display_name))

        f.write('\tid: {},\n'.format(name['id']))
        f.write('\tenglish: "{}",\n'.format(name['English']))

        f.write('};\n\n')


def main():
    names = read_in()
    write(names)

if __name__ == '__main__':
    main()
